version: "3.5"

networks:
  
  edge_net:
    driver: bridge
    name: edge_net


services:

  eu_ifas_1:
    image: beamcampus/swai_edge:latest
    container_name: eu_ifas_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=ifas-d-1
      - SWAI_SCAPE_NAME=IFAS EU Dairy 1
      - SWAI_CONTINENTS=Europe
      - SWAI_MAX_COUNTRIES=2
      - SWAI_MAX_FARMS_PER_COUNTRY=5
      - SWAI_INIT_ANIMALS_PER_FARM=2

  eu_ifas_2:
    image: beamcampus/swai_edge:latest
    container_name: eu_ifas_2
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=ifas-d-2
      - SWAI_SCAPE_NAME=IFAS EU Dairy 2
      - SWAI_CONTINENTS=Europe
      - SWAI_MAX_COUNTRIES=4
      - SWAI_MAX_FARMS_PER_COUNTRY=5
      - SWAI_INIT_ANIMALS_PER_FARM=2

  eu_mansonta_1:
    image: beamcampus/swai_edge:latest
    container_name: eu_mansonta_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=eu-man-d-1
      - SWAI_SCAPE_NAME=MANSONTA EU Dairy 2
      - SWAI_CONTINENTS=Europe
      - SWAI_MAX_COUNTRIES=2
      - SWAI_MAX_FARMS_PER_COUNTRY=5
      - SWAI_INIT_ANIMALS_PER_FARM=2


  eu_enevilur_1:
    image: beamcampus/swai_edge:latest
    container_name: eu_enevilur_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=enev-d-1
      - SWAI_SCAPE_NAME=ENEVILUR EU Dairy 1
      - SWAI_CONTINENTS=Europe
      - SWAI_MAX_COUNTRIES=3
      - SWAI_MAX_FARMS_PER_COUNTRY=5
      - SWAI_INIT_ANIMALS_PER_FARM=2


  eu_pactor_gimble_1:
    image: beamcampus/swai_edge:latest
    container_name: eu_pactor_gimble_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=eu-pg-d-1
      - SWAI_SCAPE_NAME=PACTOR&FIMBLE EU Dairy 1
      - SWAI_CONTINENTS=Europe
      - SWAI_MAX_COUNTRIES=3
      - SWAI_MAX_FARMS_PER_COUNTRY=5
      - SWAI_INIT_ANIMALS_PER_FARM=2


