version: "3.5"


networks:
  
  edge_net:
    driver: bridge
    name: edge_net


services:

  na_ifas_1:
    image: beamcampus/swarm_wars_edge:latest
    container_name: na_ifas_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=na-ifas-d-1
      - SWAI_SCAPE_NAME=EUIFAS NA Dairy 1
      - SWAI_CONTINENTS=North America, South America
      - SWAI_MAX_COUNTRIES=4
      - SWAI_MAX_FARMS_PER_COUNTRY=2
      - SWAI_INIT_ANIMALS_PER_FARM=2

  as_ifas_2:
    image: beamcampus/swarm_wars_edge:latest
    container_name: as_ifas_2
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=ifas-d-2
      - SWAI_SCAPE_NAME=EUIFAS EU Dairy 2
      - SWAI_CONTINENTS=Asia
      - SWAI_MAX_COUNTRIES=4
      - SWAI_MAX_FARMS_PER_COUNTRY=2
      - SWAI_INIT_ANIMALS_PER_FARM=2

  as_vb_1:
    image: beamcampus/swarm_wars_edge:latest
    container_name: as_vb_1
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY
      - SWAI_SCAPE_ID=asaf-vb-d-1
      - SWAI_SCAPE_NAME=GSG VEN BROO ASE Dairy 1
      - SWAI_CONTINENTS=Africa,Asia
      - SWAI_MAX_COUNTRIES=4
      - SWAI_MAX_FARMS_PER_COUNTRY=2
      - SWAI_INIT_ANIMALS_PER_FARM=2


