networks:

  edge_net:
    driver: bridge
    name: edge_net


services:


  aco-egypt:
    image: beamcampus/swai_aco:latest
    container_name: aco-egypt
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-egypt"
    - SWAI_EDGE_LAT=26.8206
    - SWAI_EDGE_LON=30.8025


  aco-nigeria:
    image: beamcampus/swai_aco:latest
    container_name: aco-nigeria
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-nigeria"
    - SWAI_EDGE_LAT=9.082
    - SWAI_EDGE_LON=8.6753

  aco-turkey:
    image: beamcampus/swai_aco:latest
    container_name: aco-turkey
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-turkey"
    - SWAI_EDGE_LAT=38.9637
    - SWAI_EDGE_LON=35.2433  

  
  aco-israel:
    image: beamcampus/swai_aco:latest
    container_name: aco-israel
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-israel"
    - SWAI_EDGE_LAT=31.0461
    - SWAI_EDGE_LON=34.8516
  
  
  aco-iceland:
    image: beamcampus/swai_aco:latest
    container_name: aco-iceland
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-iceland"
    - SWAI_EDGE_LAT=64.9631
    - SWAI_EDGE_LON=-19.0208


  aco-poland:
    image: beamcampus/swai_aco:latest
    container_name: aco-poland
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-poland"
    - SWAI_EDGE_LAT=51.9194
    - SWAI_EDGE_LON=19.1451
  
  aco-spain-barcelona:
    image: beamcampus/swai_aco:latest
    container_name: aco-spain-barcelona
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-spain"
    - SWAI_EDGE_LAT=40.4637
    - SWAI_EDGE_LON=3.7492

  aco-portugal-lisbon:
    image: beamcampus/swai_aco:latest
    container_name: aco-portugal-lisbon
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-portugal"
    - SWAI_EDGE_LAT=38.7223
    - SWAI_EDGE_LON=9.1393

  
  aco-usa-new-york:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-new-york
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-new-york"
      - SWAI_EDGE_LAT=40.7128
      - SWAI_EDGE_LON=-74.0060


  aco-canada-ontario:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada-ontario
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada-ontario"
      - SWAI_EDGE_LAT=51.2538
      - SWAI_EDGE_LON=-85.3232

  
  aco-netherlands:
    image: beamcampus/swai_aco:latest
    container_name: aco-netherlands
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-netherlands"
    - SWAI_EDGE_LAT=52.1326
    - SWAI_EDGE_LON=5.2913


