networks:

  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-sidney-aus:
    image: beamcampus/swai_aco:latest
    container_name: aco-sidney-aus
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-sidney-aus"
    - SWAI_EDGE_LAT=-33.8688
    - SWAI_EDGE_LON=151.2093
    - SWAI_EDGE_COUNTRY="Australia"
    - SWAI_EDGE_CITY="Sydney"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=3

  aco-rio-brazil:
    image: beamcampus/swai_aco:latest
    container_name: aco-rio-brazil
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-rio-brazil"
    - SWAI_EDGE_LAT=-22.9068
    - SWAI_EDGE_LON=-43.1729
    - SWAI_EDGE_COUNTRY="Brazil"
    - SWAI_EDGE_CITY="Rio"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=2


  aco-tunis-tunisia:
    image: beamcampus/swai_aco:latest
    container_name: aco-tunis-tunisia
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-tunis-tunisia"
    - SWAI_EDGE_LAT=36.8065
    - SWAI_EDGE_LON=10.1815
    - SWAI_EDGE_COUNTRY="Tunisia"
    - SWAI_EDGE_CITY="Tunis"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=1
    - 



