networks:

  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-east-europe:
    image: beamcampus/swai_aco:latest
    container_name: aco-east-europe
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-east-europe"
    - SWAI_EDGE_LAT=50.4501
    - SWAI_EDGE_LON=30.5234


  aco-greece:
    image: beamcampus/swai_aco:latest
    container_name: aco-greece
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-greece"
    - SWAI_EDGE_LAT=39.0742
    - SWAI_EDGE_LON=21.8243

  aco-ukraine:
    image: beamcampus/swai_aco:latest
    container_name: aco-ukraine
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-ukraine"
    - SWAI_EDGE_LAT=48.3794
    - SWAI_EDGE_LON=31.1656

  aco-uk-london:
    image: beamcampus/swai_aco:latest
    container_name: aco-uk-london
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-uk-london"
    - SWAI_EDGE_LAT=51.5074
    - SWAI_EDGE_LON=-0.1278

  aco-uk-scotland:
    image: beamcampus/swai_aco:latest
    container_name: aco-uk-scotland
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-uk-scotland"
    - SWAI_EDGE_LAT=56.4907
    - SWAI_EDGE_LON=-4.2026

  aco-argentina:
    image: beamcampus/swai_aco:latest
    container_name: aco-argentina
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-argentina"
    - SWAI_EDGE_LAT=-38.4161
    - SWAI_EDGE_LON=-63.6167


  aco-chile:
    image: beamcampus/swai_aco:latest
    container_name: aco-chile
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-chile"
    - SWAI_EDGE_LAT=-35.6751
    - SWAI_EDGE_LON=-71.543

  aco-italy-rome:
    image: beamcampus/swai_aco:latest
    container_name: aco-italy-rome
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-italy-rome"
    - SWAI_EDGE_LAT=41.9028
    - SWAI_EDGE_LON=12.4964

    
  aco-france:
    image: beamcampus/swai_aco:latest
    container_name: aco-france
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-france"
    - SWAI_EDGE_LAT=46.6034
    - SWAI_EDGE_LON=1.8883

  aco-usa-california:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-california
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-usa-california"
    - SWAI_EDGE_LAT=36.7783
    - SWAI_EDGE_LON=-119.4179

  aco-usa-texas:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-texas
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-usa-texas"
    - SWAI_EDGE_LAT=31.9686
    - SWAI_EDGE_LON=-99.9018

  aco-belgium:
    image: beamcampus/swai_aco:latest
    container_name: aco-belgium
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-belgium"
    - SWAI_EDGE_LAT=50.5039
    - SWAI_EDGE_LON=4.4699

  aco-switzerland:
    image: beamcampus/swai_aco:latest
    container_name: aco-switzerland
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-switzerland"
    - SWAI_EDGE_LAT=46.8182
    - SWAI_EDGE_LON=8.2275

  aco-sweden:
    image: beamcampus/swai_aco:latest
    container_name: aco-sweden
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-sweden"
    - SWAI_EDGE_LAT=60.1282
    - SWAI_EDGE_LON=18.6435

  aco-greenland:
    image: beamcampus/swai_aco:latest
    container_name: aco-greenland
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-greenland"
    - SWAI_EDGE_LAT=71.7069
    - SWAI_EDGE_LON=-42.6043

  aco-germany:
    image: beamcampus/swai_aco:latest
    container_name: aco-germany
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-germany"
    - SWAI_EDGE_LAT=51.1657
    - SWAI_EDGE_LON=10.4515

