networks:
  
  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-canada:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada"
      - SWAI_EDGE_LAT=56.1304
      - SWAI_EDGE_LON=-106.3468

  aco-usa:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa"
      - SWAI_EDGE_LAT=37.0902
      - SWAI_EDGE_LON=-95.7129

  aco-canada-quebec:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada-quebec
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada-quebec"
      - SWAI_EDGE_LAT=52.9399
      - SWAI_EDGE_LON=-73.5491

  aco-east-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-east-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-east-africa"
    - SWAI_EDGE_LAT=-1.2921
    - SWAI_EDGE_LON=36.8219
    
  
  aco-usa-hawaii:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-hawaii
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-hawaii"
      - SWAI_EDGE_LAT=20.7984
      - SWAI_EDGE_LON=-156.3319


  aco-south-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-south-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="swai-aco-south-africa"
    - SWAI_EDGE_LAT=-30.5595
    - SWAI_EDGE_LON=22.9375

  aco-north-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-north-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-north-africa"
    - SWAI_EDGE_LAT=26.3351
    - SWAI_EDGE_LON=17.2283

  aco-west-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-west-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-west-africa"
    - SWAI_EDGE_LAT=9.082
    - SWAI_EDGE_LON=8.6753



  aco-peru:
    image: beamcampus/swai_aco:latest
    container_name: aco-peru
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-peru"
      - SWAI_EDGE_LAT=-9.19
      - SWAI_EDGE_LON=-75.0152