networks:
  
  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-canada:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada"
      - SWAI_EDGE_LAT=56.1304
      - SWAI_EDGE_LON=-106.3468

  aco-usa:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa"
      - SWAI_EDGE_LAT=37.0902
      - SWAI_EDGE_LON=-95.7129

  aco-usa-california:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-california
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-california"
      - SWAI_EDGE_LAT=36.7783
      - SWAI_EDGE_LON=-119.4179

  aco-usa-texas:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-texas
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-texas"
      - SWAI_EDGE_LAT=31.9686
      - SWAI_EDGE_LON=-99.9018

  aco-usa-new-york:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-new-york
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-new-york"
      - SWAI_EDGE_LAT=40.7128
      - SWAI_EDGE_LON=-74.0060


  aco-canada-ontario:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada-ontario
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada-ontario"
      - SWAI_EDGE_LAT=51.2538
      - SWAI_EDGE_LON=-85.3232
  
  aco-canada-quebec:
    image: beamcampus/swai_aco:latest
    container_name: aco-canada-quebec
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-canada-quebec"
      - SWAI_EDGE_LAT=52.9399
      - SWAI_EDGE_LON=-73.5491

  aco-usa-florida:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-florida
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-florida"
      - SWAI_EDGE_LAT=27.9944
      - SWAI_EDGE_LON=-81.7603    
  
  aco-usa-hawaii:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-hawaii
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-usa-hawaii"
      - SWAI_EDGE_LAT=20.7984
      - SWAI_EDGE_LON=-156.3319        






  aco-mexico:
    image: beamcampus/swai_aco:latest
    container_name: aco-mexico
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-mexico"
      - SWAI_EDGE_LAT=23.6345
      - SWAI_EDGE_LON=-102.5528  

  aco-brazil:
    image: beamcampus/swai_aco:latest
    container_name: aco-brazil
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-brazil"
      - SWAI_EDGE_LAT=-14.235
      - SWAI_EDGE_LON=-51.9253


  aco-argentina:
    image: beamcampus/swai_aco:latest
    container_name: aco-argentina
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-argentina"
      - SWAI_EDGE_LAT=-38.4161
      - SWAI_EDGE_LON=-63.6167


  aco-chile:
    image: beamcampus/swai_aco:latest
    container_name: aco-chile
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-chile"
      - SWAI_EDGE_LAT=-35.6751
      - SWAI_EDGE_LON=-71.543


  aco-peru:
    image: beamcampus/swai_aco:latest
    container_name: aco-peru
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-peru"
      - SWAI_EDGE_LAT=-9.19
      - SWAI_EDGE_LON=-75.0152