networks:

  edge_net:
    driver: bridge
    name: edge_net


services:


  aco-china-beijing:
    image: beamcampus/swai_aco:latest
    container_name: aco-china-beijing
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-china-beijing"
    - SWAI_EDGE_LAT=39.9042
    - SWAI_EDGE_LON=116.4074
    - SWAI_EDGE_COUNTRY="China"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=6
    
  aco-egypt-cairo:
    image: beamcampus/swai_aco:latest
    container_name: aco-egypt-cairo
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-egypt-cairo"
    - SWAI_EDGE_LAT=30.0444
    - SWAI_EDGE_LON=31.2357
    - SWAI_EDGE_COUNTRY="Egypt"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=7

  aco-germany-berlin:
    image: beamcampus/swai_aco:latest
    container_name: aco-germany-berlin
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-germany-berlin"
    - SWAI_EDGE_LAT=52.5200
    - SWAI_EDGE_LON=13.4050
    - SWAI_EDGE_COUNTRY="Germany"
    - SWAI_EDGE_IS_CONTAINER=0
    - SWAI_EDGE_SCAPES_CAP=3 

