networks:

  edge_net:
    driver: bridge
    name: edge_net


services:


  aco-athens-greece:
    image: beamcampus/swai_aco:latest
    container_name: aco-athens-greece
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-athens-greece"
    - SWAI_EDGE_LAT=37.9838
    - SWAI_EDGE_LON=23.7275
    - SWAI_EDGE_COUNTRY="Greece"
    - SWAI_EDGE_IS_CONTAINER="true"
    - SWAI_EDGE_CITY="Athens"
    - SWAI_EDGE_IS_CONTAINER="false"
    - SWAI_EDGE_SCAPES_CAP=5

  aco-uk-london:
    image: beamcampus/swai_aco:latest
    container_name: aco-uk-london
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-uk-london"
    - SWAI_EDGE_LAT=51.5074
    - SWAI_EDGE_LON=-0.1278
    - SWAI_EDGE_COUNTRY="UK"
    - SWAI_EDGE_IS_CONTAINER="true"
    - SWAI_EDGE_CITY="London"
    - SWAI_EDGE_SCAPES_CAP=4

  aco-italy-rome:
    image: beamcampus/swai_aco:latest
    container_name: aco-italy-rome
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-italy-rome"
    - SWAI_EDGE_LAT=41.9028
    - SWAI_EDGE_LON=12.4964
    - SWAI_EDGE_COUNTRY="Italy"
    - SWAI_EDGE_IS_CONTAINER="false"