networks:

  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-south-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-south-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="swai-aco-south-africa"
    - SWAI_EDGE_LAT=-30.5595
    - SWAI_EDGE_LON=22.9375

  aco-north-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-north-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-north-africa"
    - SWAI_EDGE_LAT=26.3351
    - SWAI_EDGE_LON=17.2283

  aco-west-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-west-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-west-africa"
    - SWAI_EDGE_LAT=9.082
    - SWAI_EDGE_LON=8.6753

  aco-egypt:
    image: beamcampus/swai_aco:latest
    container_name: aco-egypt
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-egypt"
    - SWAI_EDGE_LAT=26.8206
    - SWAI_EDGE_LON=30.8025


  aco-nigeria:
    image: beamcampus/swai_aco:latest
    container_name: aco-nigeria
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-nigeria"
    - SWAI_EDGE_LAT=9.082
    - SWAI_EDGE_LON=8.6753


  aco-congo:
    image: beamcampus/swai_aco:latest
    container_name: aco-congo
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-congo"
    - SWAI_EDGE_LAT=-4.0383
    - SWAI_EDGE_LON=21.7587

  aco-madagascar:
    image: beamcampus/swai_aco:latest
    container_name: aco-madagascar
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-madagascar"
    - SWAI_EDGE_LAT=-18.7669
    - SWAI_EDGE_LON=46.8691


  aco-east-africa:
    image: beamcampus/swai_aco:latest
    container_name: aco-east-africa
    restart: always
    networks:
    - edge_net
    environment:
    - SWAI_EDGE_API_KEY="aco-east-africa"
    - SWAI_EDGE_LAT=-1.2921
    - SWAI_EDGE_LON=36.8219
