networks:
  
  edge_net:
    driver: bridge
    name: edge_net


services:

  aco-toronto-canada:
    image: beamcampus/swai_aco:latest
    container_name: aco-toronto-canada
    restart: always
    networks:
      - edge_net
    environment:      
      - SWAI_EDGE_API_KEY="aco-toronto-canada"
      - SWAI_EDGE_LAT=56.1304
      - SWAI_EDGE_LON=-106.3468
      - SWAI_EDGE_COUNTRY="Canada"
      - SWAI_EDGE_IS_CONTAINER="false"
      - SWAI_EDGE_SCAPES_CAP=3
      - SWAI_EDGE_CITY="Toronto"
      - SWAI_EDGE_CCA2="CA"

  aco-brussels-belgium:
    image: beamcampus/swai_aco:latest
    container_name: aco-brussels-belgium
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY="aco-brussels-belgium"
      - SWAI_EDGE_LAT=50.8503
      - SWAI_EDGE_LON=4.3517
      - SWAI_EDGE_COUNTRY="Belgium"
      - SWAI_EDGE_IS_CONTAINER="false"
      - SWAI_EDGE_SCAPES_CAP=4
      - SWAI_EDGE_CITY="Brussels"
      - SWAI_EDGE_CCA2="BE"

  aco-usa-manchester:
    image: beamcampus/swai_aco:latest
    container_name: aco-usa-manchester
    restart: always
    networks:
      - edge_net
    environment:
      - SWAI_EDGE_API_KEY="aco-usa-manchester"
      - SWAI_EDGE_LAT=53.4808
      - SWAI_EDGE_LON=-2.2426
      - SWAI_EDGE_COUNTRY="USA"
      - SWAI_EDGE_IS_CONTAINER="true"
      - SWAI_EDGE_SCAPES_CAP=5
      - SWAI_EDGE_CITY="Manchester"
      - SWAI_EDGE_CCA2="US"



